In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


In [ ]:
data=pd.read_csv('Social_Network_Ads.csv')
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
#remove user id
data1=data.drop('User ID',axis=1)

In [ ]:
data1.head()

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [ ]:
#one hot encoding
data1=pd.get_dummies(data1)

In [ ]:
data1.head()

Age  EstimatedSalary  Purchased  Gender_Female  Gender_Male
0   19            19000          0              0            1
1   35            20000          0              0            1
2   26            43000          0              1            0
3   27            57000          0              1            0
4   19            76000          0              0            1

In [ ]:
X=data1.drop('Purchased',axis=1)
Y=data1['Purchased']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

***SVM***

In [ ]:
#import SVM
from sklearn.svm import SVC
#Instance,specify kernal type
clf_svm=SVC(kernel='linear')



In [ ]:
clf_svm=clf_svm.fit(X_train,Y_train)
y_predict=clf_svm.predict(X_test)

In [ ]:
#Evaluate model
from sklearn.metrics import accuracy_score,confusion_matrix


In [ ]:
confusion_matrix(Y_test,y_predict)

array([[48,  4],
       [ 9, 19]])

In [ ]:
accuracy_score(Y_test,y_predict)

0.8375

**using rbf kernal in SVM**

In [ ]:
clf_svm2=SVC(kernel='rbf')
clf_svm2=clf_svm2.fit(X_train,Y_train)
y_predict2=clf_svm2.predict(X_test)

In [ ]:
confusion_matrix(Y_test,y_predict2)

array([[49,  3],
       [18, 10]])

In [ ]:
accuracy_score(Y_test,y_predict2)

0.7375

***Do min max scaling and then do regression***

In [ ]:
from sklearn import preprocessing

In [ ]:
X.head()

Age  EstimatedSalary  Gender_Female  Gender_Male
0   19            19000              0            1
1   35            20000              0            1
2   26            43000              1            0
3   27            57000              1            0
4   19            76000              0            1

In [ ]:
X.columns

Index(['Age', 'EstimatedSalary', 'Gender_Female', 'Gender_Male'], dtype='object')

In [ ]:
X1=X

In [ ]:
min_max_scalar=preprocessing.MinMaxScaler(feature_range=(0,1))


In [ ]:
X1=min_max_scalar.fit_transform(X1)

In [ ]:
X1=pd.DataFrame(X1,columns=['Age', 'EstimatedSalary', 'Gender_Female', 'Gender_Male'])

In [ ]:
X.drop(['Age', 'EstimatedSalary', 'Gender_Female', 'Gender_Male'],inplace=True,axis=1)
X=pd.concat([X,X1],axis=1)

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)



In [ ]:
clf_svm3=SVC(kernel='linear')
clf_svm3=clf_svm3.fit(X_train,Y_train)
y_predict3=clf_svm3.predict(X_test)
accuracy_score(Y_test,y_predict3)

0.875

In [ ]:
clf_svm4=SVC(kernel='rbf')
clf_svm4=clf_svm4.fit(X_train,Y_train)
y_predict4=clf_svm4.predict(X_test)
accuracy_score(Y_test,y_predict4)

0.925

***DECISION TREE***

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
X=data1.drop('Purchased',axis=1)
Y=data1['Purchased']


In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y)

In [ ]:
dlt=DecisionTreeClassifier()
dlt=dlt.fit(X_train,Y_train)
y_predict5=dlt.predict(X_test)

In [ ]:
confusion_matrix(Y_test,y_predict5)

array([[66,  6],
       [ 5, 23]])

In [ ]:
accuracy_score(Y_test,y_predict5)

0.89

In [ ]:
#min max and decision tree
min_max_scalar=preprocessing.MinMaxScaler(feature_range=(0,1))
X1=min_max_scalar.fit_transform(X1)

In [ ]:
dlt=DecisionTreeClassifier()
dlt=dlt.fit(X_train,Y_train)
y_predict6=dlt.predict(X_test)

In [ ]:
accuracy_score(Y_test,y_predict6)

0.8375

This shows min max scaling has no effect on decision tree as decision tree isnot based on distance

***RANDOM FOREST ALGORITHM***

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf=RandomForestClassifier()
rf=rf.fit(X_train,Y_train)
rlf_predict=rf.predict(X_test)

In [ ]:
confusion_matrix(Y_test,rlf_predict)

array([[47,  5],
       [ 3, 25]])

In [ ]:
accuracy_score(Y_test,rlf_predict)

0.9

**High accuracy and best method**